### ISSUE TITLE
Problem in Installation

### ISSUE THREAD

**Issue by Fadavvi** [sbidy/privacyIDEA-ADFSProvider#1]
Hi dear sbidy,  

I installed PrivacyIdea And its work very well. My PrivacyIdea server joined to an Active directory Server and Fetched Users list too.

I found privacyIDEA-ADFSProvider in Github, So I installed MS CA and MS AD FS (MS windows 2012r2) and linked this services together (than work well).
I build privacyIDEA-ADFSProvider project with VS 2015.

Signing Option in VS:

![sign](https://user-images.githubusercontent.com/21213484/32143384-a9548c9e-bcbd-11e7-9b78-25756b649a19.png)

Assembly:

![assem](https://user-images.githubusercontent.com/21213484/32143388-b705d5e6-bcbd-11e7-813b-cbe08cc50de0.png)

​( GUID was changed with String than provided by MS AD FS)

And I changed config.xml values with my PrivacyIdea server's information. (IP/User/Pass/Realm)

and build the project and copy .dll file to correct location. I checked MS AD FS services then try to run Powershell script for installation but I found a problem!! :

​
![error](https://user-images.githubusercontent.com/21213484/32143390-bc97debe-bcbd-11e7-966f-1d9815085b49.png)

What is the problem?? Should I change PublicKeyToken value too?? If yes, I should change it with what?? or where I go wrong? Can you help me??

[[ I know this is not a code issue. but I post problem in community 2 time but nobody answer me ]]

Best Regards,
Milad

**Comment by sbidy** [comment]
Hey Milad,

yes that's correct. If you sign the binary you'll get a new Public Key Token for the dll. This new PK-Token has to be replaced in the Power Shell script.

To get the new token ID start the Visual Studio x64 Win64 Command Prompt, and run the SN command with the -T parameter and the location of the file. Run `SN -T "<theProjectFolder>\bin\Debug\<NameOfYourProvider.dll"` --> more [here](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool) .You'll get the PK-Token-ID

Now you should change the ID at the Power Shell script (line 8):
`$typeName = "privacyIDEAADFSProvider.Adapter, privacyIDEAADFSProvider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=<HERE>"`

Now you can register the provider without an error.

For more info check [this blog post](https://blogs.technet.microsoft.com/cloudpfe/2014/02/01/how-to-create-a-custom-authentication-provider-for-active-directory-federation-services-on-windows-server-2012-r2-part-2/)

**Comment by Fadavvi** [comment]
thanks a bunch dear Stephan for your quick response. It's work for me. 

freundliche Grüße. 
Milad.

**Comment by sbidy** [comment]
Ok, cool!
Danke :)
