### ISSUE TITLE
Wrong user used in second step

### ISSUE THREAD

**Issue by cornelinux** [sbidy/privacyIDEA-ADFSProvider#14]
We realized that a wrong username can be used in the authentication request of the second step.

We configured a service account to do triggerchallenge to send SMS.

# Observation

We observe the following:

1. **UserA** enters his windows credentials. We see a ``validate/triggerchallenge`` call in privacyIDEA for **UserA**. The user receives the SMS on his phone.

2. On another browser a **UserB** enters his windows credentials. We see a ``validate/triggerchallenge`` call in privacyIDEA for **UserB**. The user receives the SMS on his phone.

3. Now **UserA** enters his OTP value. But now an API call is sent to privacyIDEA ``validate/check`` with the username **UserB**. Of course authentication fails.

# Analysis

Obvious the ``IdentityClaim`` you are using are not bound to the right session or is only a current snapshot.

The ``username`` is currently defined as a member variable of the Authenticator Class. Obviously ADFS does not create a new instance of the class on each request or the variable is shared over all instances.
https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/f7823a0ce385946abed7b7a6ce8971daa3873638/privacyIDEAADFSProvider/Adapter.cs#L22
Thus the second user trying to authenticate will overwrite the username causing the first user fail to login.

# One possible solution

I think a possible solution could be to add the username and realm as hidden fields to the [login form](https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/master/privacyIDEAADFSProvider/AuthPage.html) and also read the username from the HTTP request [just like the otp value](https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/f7823a0ce385946abed7b7a6ce8971daa3873638/privacyIDEAADFSProvider/Adapter.cs#L158).

Please drop me a note, if you need any more information or assistance.

**Comment by sbidy** [comment]
Hey @cornelinux ! Thanks for the report!
So I assumed that the ADFS creates a object for each request from the class ... But that seems not correct 😞 .

I'll look into that and try to tied the realm/username to the corresponding "session". A hidden HTML form field can be a feasible solution. Thank you for that suggestion! 😉

**Comment by tedbear** [comment]
Hi sbidy,

I was working/debugging with cornelinux on this issue. Let me know if you need me for any testing etc, as I have a team of 25 colleagues more or less just sitting and waiting to test (and use the plugin when it works) this plugin for ADFS/privacyidea.
Also: Do you have any idea of how long it would possibly take for you to fix the issue?

Thank you in advance!

Best regards,
Teddy Strand

**Comment by sbidy** [comment]
I'm still working at the issue at the moment 😉 ... maybe a fix is coming today.

**Comment by sbidy** [comment]
Please check the 1.3.3a version - I added the username and realm to hidden input fields and use this for the OTP request to the ID3A. This should fix the problem.

!! -> the install script should be updated too (changed version number) !!

**Comment by cornelinux** [comment]
Hi @sbidy 
thanks for the realy quick respsone.
When I look at this line, https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/3fc31c7885b589c6b591c7d5e8771ce96d39fcb7/privacyIDEAADFSProvider/Adapter.cs#L170
I think it must be ``session_user`` in the parameters and not ``username``.
Thx
Cornelius

PS: I added a quick pull request :-)

**Comment by sbidy** [comment]
Bug fixed with last commit but still not in the last release (1.3.3).
New release is coming with bug fix for #15.

**Comment by tedbear** [comment]
Hi @sbidy 
Thanks for the update. Do you reckon the new release will be available later today?

**Comment by sbidy** [comment]
Sorry for the delay 😞 ... pre-Christmas-stress 🎄 ...
I'll publish an new 1.3.3 pre-realase "now".
