### ISSUE TITLE
Using Email as username

### ISSUE THREAD

**Issue by touchonesolutions** [sbidy/privacyIDEA-ADFSProvider#25]
Hi, I have deplyed version 1.3.4 and got it working perfectly.

Now I have changed the login username on ADFS to accept email address as username which works, I have set PID server to use email address as userID, but when doing a full test and I check the PID aufit logs the username is not coming in as an email address and fails authentication because the user cannot be found.

Is there a way to push the full username from ADFS which in this case is the email address to my PID server?

Thanks

**Comment by touchonesolutions** [comment]
Sorry I think this is a duplicate from abother 2 issues already on your to-do list.

Sorry.

**Comment by sbidy** [comment]
Duplicate of #23
