### ISSUE TITLE
Installation problem with v1.3.4

### ISSUE THREAD

**Issue by kabelbruch** [sbidy/privacyIDEA-ADFSProvider#26]
Hello, everybody,

I get the following message during the installation.
I already tried the v1.2 with the same result.
I guess I miss something, but don't get it ;-)

Greetings, Thomas

Register-AdfsAuthenticationProvider : The external authentication method
privacyIDEA-ADFSProvider could not be loaded. Could not load file or assembly
'privacyIDEA-ADFSProvider, Version=1.3.4.0, Culture=neutral,
PublicKeyToken=bf6bdb60967d5ecc' or one of its dependencies. The system cannot
find the file specified.
At C:\Program Files\privacyIDEAProvider\Install-ADFSProvider.ps1:42 char:1
+ Register-AdfsAuthenticationProvider -TypeName $typeName -Name
"privacyIDEA-ADFSP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-AdfsAuthenticationPr
   ovider], AuthenticationMethodLoadException
    + FullyQualifiedErrorId : The external authentication method privacyIDEA-A
   DFSProvider could not be loaded. Could not load file or assembly 'privacyI
  DEA-ADFSProvider, Version=1.3.4.0, Culture=neutral, PublicKeyToken=bf6bdb6
 0967d5ecc' or one of its dependencies. The system cannot find the file spe
cified.,Microsoft.IdentityServer.Management.Commands.AddExternalAuthProvid
erCommand

**Comment by sbidy** [comment]
In this case you should check the path in the PowerShell Installer Script. Please follow the installation instructions in the readme. Please use the releases not the repository it self.

I've tested the installation on Windows Server 2016, 2012, 2012 R2 and 2019 (latest).

**Comment by sbidy** [comment]
Do you have "unblocked" all dll and ps1 files? Please run the Power Shell with administrative privileges.

**Comment by sbidy** [comment]
seems to be fixed
