### ISSUE TITLE
Build Error pfx

### ISSUE THREAD

**Issue by touchonesolutions** [sbidy/privacyIDEA-ADFSProvider#27]
Hi, I have been using v1.3.4 for a few weeks and love it.

The one thing and only thing I wanted to change is the title page, just so that it matches in with the rest of the site.

I have downloaded the raw code of 1.3.4 and 1.3.5 and I know where to change this value but when I try to build the project to get the new dll file I get an error saying that the pfx file is missing.

What can I do about this?

Thanks
Martin

**Comment by touchonesolutions** [comment]
Ok just an update to this and also to issue 26.

I get the same install errors as issue 26 if I compile/build the project again, even if I create my own certificate there are still issues.  So maybe some high level instructions on building the project again would be useful.

One thing to note which maybe the main issue with building.  When I load the project files I get a warning regarding .net version 4.5 as I am using v4.6 with Visual Studio 2017.  I have tried many ways of getting the v4.5 target installed/added to VS but it doesnt seem to work.

Thanks
Martin

**Comment by sbidy** [comment]
The building itself is not really difficult. As you mentioned you have to create a code signing certificate (PFX). Please also be aware of the changing Public Key Token in the Power Shell script - see here https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method#build-the-adapter

You have to unblock the DLL and the PS1 too.

**Comment by touchonesolutions** [comment]
Hi Sbidy, thanks for your comments and link.  I have solved the issue which is more to do with my lack of knowledge.  I created a new signing certificate and then updated the Public Key Token in the setup/install script and now its all working.

Thanks again.
Martin

**Comment by sbidy** [comment]
Cool. Thank you for the update! 
If you have some improvements or bug fixes, you welcome to create a pull :)
