### ISSUE TITLE
Make FriendlyNames adjustable in Config

### ISSUE THREAD

**Issue by fefaul** [sbidy/privacyIDEA-ADFSProvider#29]
Hi,

is there some way to make FriendlyNames for the users choice adjustable through the config file? 
 This would allow us to choose a more user friendly name like "Company XZY OTP" or more well know name. This could avoid user confusion.

AdapterMetadata.cs
```
friendlyNames.Add(new CultureInfo("en-us").LCID, "privacyIDEA ADFS authentication provider");
friendlyNames.Add(new CultureInfo("de-de").LCID, "privacyIDEA ADFS Authentikationsprovider");
```

**Comment by sbidy** [comment]
In the new version the "HTML page titel filed can be defined in the config.
Still in testing.
