### ISSUE TITLE
Windows Configuration for using privacyIDEA-ADFSProvider

### ISSUE THREAD

**Issue by Fadavvi** [sbidy/privacyIDEA-ADFSProvider#3]
Hi again,
I installed privacyIDEA-ADFSProvider-1.1-beta by your help. 

![ad fs](https://user-images.githubusercontent.com/21213484/32686974-9cd7be2e-c6c6-11e7-87b2-42836260f6ad.png)

but still windows authentication method works and not any OTP required for login. 
I set config.xml values with correct data, URL/User/Password/Realm. In MFA Users/Groups box, I test Administrator Group, Users group, Empty list and a single Administrator user but nothing changed! 

Any suggestion or documentation can help me. 

BR, 
Milad

**Comment by sbidy** [comment]
Hey,
can you please run the DebugView [Link](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) at the ADFS and report me the Debug output from the provider.
Please check also the EventLog for corresponding Events.

Maybe there are some exceptions or failures.

**Comment by Fadavvi** [comment]
I ran the program at AD FS server and try to login with client than joined to AD. And log is :

00000001	0.00000000	45760156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000002	0.00036393	45760156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000003	0.99992174	45770156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000004	1.00027287	45770156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000005	1.99957144	45780156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000006	1.99996495	45780156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000007	2.99935889	45790156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped
00000037	18.06217384	45940781250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000038	18.06242371	45940781250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000039	18.83280373	[FFFFE000CC9EB010] WskProIRPGetAddrInfo is called.	
00000040	18.83281136	[bind=FFFFE000CBF22DA0] Binding reference count++ = 30 (status = 00000000, impersonation= 2).	
00000041	18.83281517	[FFFFE000CCEB1230] Request reference count++ = 3.	
00000042	18.83286285	[FFFFE000CCEB1230] RPC method type = 1: rpc-method succeeded, queue to rpc-pending-list.	
00000043	18.83286476	[FFFFE000CCEB1230] Request reference count-- = 2.	
00000044	18.83345985	[FFFFE000CCEB1230] WskKnrRpcComplete: rpc calls back for completion.	
00000045	18.83346367	[FFFFE000CCEB1230] WskKnrCompletePending: complete pending request (rpc=1).	
00000046	18.83347702	[FFFFE000CCEB1230] WskKnrCompleteRequest: rpc completion return status = 00000000 (reply=00000000).	
00000047	18.83347893	[FFFFE000CCEB1230] WskProAPIGetAddressInfo returned addrinfo: [addr=FFFFC0009F3762F0].	
00000048	18.83348083	[FFFFE000CCEB1230] Request reference count-- = 1.	
00000049	18.83348465	[FFFFE000CCEB1230] Request reference count-- = 0.	
00000050	18.83348656	[bind=FFFFE000CBF22DA0] Binding reference count-- = 29.	
00000051	18.83348846	[FFFFE000CCEB1230] WskKnrCompleteRequest: complete irp with IO status = 00000000.	
00000052	18.83419991	[addr=FFFFC0009F3762F0] WskProAPIFreeAddressInfo freed addrinfo.	
00000053	18.99965286	45950156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000054	19.00004387	45950156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000055	20.00005722	45960156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000099	41.98492050	[FFFFE000CCCAACF0] WskProIRPGetAddrInfo is called.	
00000100	41.98492432	[bind=FFFFE000CBF22DA0] Binding reference count++ = 31 (status = 00000000, impersonation= 2).	
00000101	41.98492813	[FFFFE000CB624490] Request reference count++ = 3.	
00000102	41.98495865	[FFFFE000CB624490] RPC method type = 1: rpc-method succeeded, queue to rpc-pending-list.	
00000103	41.98496246	[FFFFE000CB624490] Request reference count-- = 2.	
00000104	41.98558426	[FFFFE000CB624490] WskKnrRpcComplete: rpc calls back for completion.	
00000105	41.98558807	[FFFFE000CB624490] WskKnrCompletePending: complete pending request (rpc=1).	
00000106	41.98560715	[FFFFE000CB624490] WskKnrCompleteRequest: rpc completion return status = 00000000 (reply=00000000).	
00000107	41.98561096	[FFFFE000CB624490] WskProAPIGetAddressInfo returned addrinfo: [addr=FFFFC000905352C0].	
00000108	41.98561096	[FFFFE000CB624490] Request reference count-- = 1.	
00000109	41.98561096	[FFFFE000CB624490] Request reference count-- = 0.	
00000110	41.98561478	[bind=FFFFE000CBF22DA0] Binding reference count-- = 30.	
00000111	41.98561478	[FFFFE000CB624490] WskKnrCompleteRequest: complete irp with IO status = 00000000.	
00000112	41.98631668	[addr=FFFFC000905352C0] WskProAPIFreeAddressInfo freed addrinfo.	
00000113	42.00090408	46180156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000114	42.00128937	46180156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	
00000133	51.87540054	VBOXNP: DLL loaded.	
00000134	52.00071335	46280156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Stopped	
00000135	52.00113297	46280156250 - STORMINI: StorAHCI - LPM: Port 01 - Port Started	

If it is useless please tell me what should I do.

Thanks for your time.

**Comment by sbidy** [comment]
Hey, sorry haven't time in the last weeks to reproduce the problem.
What kind of OS you use? Sever 2016 or 2012 R2?
Can you also check the EventLog please?

**Comment by sbidy** [comment]
Check the EventLog under `Custom Views -> Server Rols -> Active Directory Federation Services`

**Comment by Fadavvi** [comment]
Thanks! I'll send Eventlogs soon as soon possible. Sorry for delay in response.

**Comment by Fadavvi** [comment]
Level	Date and Time	Source	Event ID	Task Category
Information	1/8/2018 13:36:27	AD FS	388	None	AD FS detected that all the service certificates have appropriate access given to the AD FS service account.
Warning	1/8/2018 13:36:27	AD FS	415	None	The SSL certificate does not contain all UPN suffix values that exist in the enterprise.  Users with UPN suffix values not represented in the certificate will not be able to Workplace-Join their devices.  For more information, see http://go.microsoft.com/fwlink/?LinkId=311954.
Information	1/8/2018 13:35:26	AD FS	100	None	"The Federation Service started successfully. The following service hosts have been added: 
Federation Server Proxy ServiceHost
https://ad.new.local:443/adfs/services/proxytrustpolicystoretransfer

MSIS0004
https://ad.new.local/adfs/fs/federationserverservice.asmx

Issuance ServiceHost
http://localhost:80/adfs/services/trust/mexsoap
https://ad.new.local:443/adfs/services/trust/proxymex/

Issuance ServiceHost
http://localhost/adfs/services/trust/proxymexsoap
https://ad.new.local:443/adfs/services/trust/proxymex/

Issuance ServiceHost
https://ad.new.local/adfs/services/trust/2005/windowstransport
https://ad.new.local/adfs/services/trust/2005/certificatemixed
https://ad.new.local:49443/adfs/services/trust/2005/certificatetransport
https://ad.new.local/adfs/services/trust/2005/usernamemixed
https://ad.new.local/adfs/services/trust/2005/kerberosmixed
https://ad.new.local/adfs/services/trust/2005/issuedtokenmixedasymmetricbasic256
https://ad.new.local/adfs/services/trust/2005/issuedtokenmixedsymmetricbasic256
https://ad.new.local/adfs/services/trust/13/kerberosmixed
https://ad.new.local/adfs/services/trust/13/certificatemixed
https://ad.new.local/adfs/services/trust/13/usernamemixed
https://ad.new.local/adfs/services/trust/13/issuedtokenmixedasymmetricbasic256
https://ad.new.local/adfs/services/trust/13/issuedtokenmixedsymmetricbasic256
net.tcp://localhost/adfs/services/trusttcp/windows

SAML Metadata
https://ad.new.local/FederationMetadata/2007-06/

Other endpoints

https://+:443/adfs/oauth2/authorize/
https://+:443/adfs/ls/
https://+:443/adfs/oauth2/token/
https://+:49443/adfs/oauth2/authorize/
https://+:49443/adfs/ls/
http://+:80/adfs/artifact/
https://+:443/adfs/Proxy/EstablishTrust/
https://+:443/adfs/backendproxytls/
https://+:443/adfs/Proxy/
http://+:80/adfs/Proxy/PrimaryWriter/
https://+:49443/adfs/portal/
https://+:443/adfs/portal/
http://+:80/adfs/probe/
"
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Proxy TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Proxy TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Proxy TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'WindowsAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Passive protocol pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Passive protocol pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'WindowsAuthentication', Context: 'Passive protocol pipeline'
Information	1/8/2018 13:35:26	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Passive protocol pipeline'
Warning	1/8/2018 13:35:24	AD FS	278	None	"The SAML artifact resolution endpoint is not configured or it is disabled. 

The artifact resolution service is not started. 

User Action 
If the artifact resolution service is required, use the AD FS Management snap-in to configure or enable the SAML artifact resolution endpoint."
Error	1/8/2018 13:35:24	AD FS	217	None	"A WS-Trust endpoint that was configured could not be opened. 

Additional Data 
Address: https://ad.new.local/adfs/services/trust/2005/windowstransport 
Mode:    WindowsTransport 

Error: 
MSIS0006: A Service Principal Name is not registered for the AD FS service account. "
Error	1/8/2018 13:35:23	AD FS	217	None	"A WS-Trust endpoint that was configured could not be opened. 

Additional Data 
Address: https://ad.new.local/adfs/services/trust/2005/windowstransport 
Mode:    WindowsTransport 

Error: 
MSIS0006: A Service Principal Name is not registered for the AD FS service account. "
Error	1/8/2018 13:35:18	AD FS	217	None	"A WS-Trust endpoint that was configured could not be opened. 

Additional Data 
Address: https://ad.new.local/adfs/services/trust/2005/windowstransport 
Mode:    WindowsTransport 

Error: 
MSIS0006: A Service Principal Name is not registered for the AD FS service account. "
Information	1/8/2018 13:35:18	AD FS	251	None	Attribute store 'Active Directory' is loaded successfully.
Information	1/8/2018 13:35:17	AD FS	349	None	"The administration service for the Federation Service started successfully. You can now use the Windows Powershell commands for AD FS to modify the Federation Service configuration. The following service hosts have been added: 
Policy Administration ServiceHost
net.tcp://localhost:1500/policy
net.tcp://localhost:1500/policy
net.tcp://localhost:1500/policy
http://ad.new.local:80/adfs/services/policystoretransfer
net.tcp://localhost:1501/adfs/services/policystoretransfer

"
Information	1/8/2018 13:35:01	AD FS	397	None	"The federation server loaded the HTTP proxy configuration from WinHTTP settings. 

HTTP Proxy:  
HTTPS Proxy:  
Bypass proxy for local addresses:  
Bypass proxy for addresses: 
 

To learn more about how to set the HTTP proxy settings for the federation server, see http://go.microsoft.com/fwlink/?LinkId=182180."
Information	1/8/2018 11:43:14	AD FS	157	None	Trust monitoring cycle completed.
Information	1/8/2018 11:43:13	AD FS	388	None	AD FS detected that all the service certificates have appropriate access given to the AD FS service account.
Warning	1/8/2018 11:43:13	AD FS	415	None	The SSL certificate does not contain all UPN suffix values that exist in the enterprise.  Users with UPN suffix values not represented in the certificate will not be able to Workplace-Join their devices.  For more information, see http://go.microsoft.com/fwlink/?LinkId=311954.
Information	1/8/2018 11:43:13	AD FS	337	None	The certificate management cycle was completed.
Information	1/8/2018 11:43:12	AD FS	156	None	Trust monitoring cycle initiated.
Information	1/8/2018 11:43:12	AD FS	390	None	AD FS detected that none of the partner certificates that are configured to be managed by the administrator are due to expire.
Information	1/8/2018 11:43:12	AD FS	386	None	AD FS detected that none of the service certificates that are configured to be managed by the administrator are due to expire.
Information	1/8/2018 11:43:12	AD FS	399	None	AD FS detected that none of the service certificates that are configured to be managed by the administrator are archived.
Information	1/8/2018 11:43:12	AD FS	336	None	The certificate management cycle was initiated.
Information	1/8/2018 11:42:12	AD FS	100	None	"The Federation Service started successfully. The following service hosts have been added: 
Federation Server Proxy ServiceHost
https://ad.new.local:443/adfs/services/proxytrustpolicystoretransfer

MSIS0004
https://ad.new.local/adfs/fs/federationserverservice.asmx

Issuance ServiceHost
http://localhost:80/adfs/services/trust/mexsoap
https://ad.new.local:443/adfs/services/trust/proxymex/

Issuance ServiceHost
http://localhost/adfs/services/trust/proxymexsoap
https://ad.new.local:443/adfs/services/trust/proxymex/

Issuance ServiceHost
https://ad.new.local/adfs/services/trust/2005/windowstransport
https://ad.new.local/adfs/services/trust/2005/certificatemixed
https://ad.new.local:49443/adfs/services/trust/2005/certificatetransport
https://ad.new.local/adfs/services/trust/2005/usernamemixed
https://ad.new.local/adfs/services/trust/2005/kerberosmixed
https://ad.new.local/adfs/services/trust/2005/issuedtokenmixedasymmetricbasic256
https://ad.new.local/adfs/services/trust/2005/issuedtokenmixedsymmetricbasic256
https://ad.new.local/adfs/services/trust/13/kerberosmixed
https://ad.new.local/adfs/services/trust/13/certificatemixed
https://ad.new.local/adfs/services/trust/13/usernamemixed
https://ad.new.local/adfs/services/trust/13/issuedtokenmixedasymmetricbasic256
https://ad.new.local/adfs/services/trust/13/issuedtokenmixedsymmetricbasic256
net.tcp://localhost/adfs/services/trusttcp/windows

SAML Metadata
https://ad.new.local/FederationMetadata/2007-06/

Other endpoints

https://+:443/adfs/oauth2/authorize/
https://+:443/adfs/ls/
https://+:443/adfs/oauth2/token/
https://+:49443/adfs/oauth2/authorize/
https://+:49443/adfs/ls/
http://+:80/adfs/artifact/
https://+:443/adfs/Proxy/EstablishTrust/
https://+:443/adfs/backendproxytls/
https://+:443/adfs/Proxy/
http://+:80/adfs/Proxy/PrimaryWriter/
https://+:49443/adfs/portal/
https://+:443/adfs/portal/
http://+:80/adfs/probe/
"
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Proxy device TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Proxy TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Proxy TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Proxy TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'WindowsAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Passive protocol TLS pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'privacyIDEA-ADFSProvider', Context: 'Passive protocol pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'CertificateAuthentication', Context: 'Passive protocol pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'WindowsAuthentication', Context: 'Passive protocol pipeline'
Information	1/8/2018 11:42:12	AD FS	106	None	An authentication provider was successfully loaded: Identifier: 'FormsAuthentication', Context: 'Passive protocol pipeline'
Warning	1/8/2018 11:42:10	AD FS	278	None	"The SAML artifact resolution endpoint is not configured or it is disabled. 

The artifact resolution service is not started. 

User Action 
If the artifact resolution service is required, use the AD FS Management snap-in to configure or enable the SAML artifact resolution endpoint."
Error	1/8/2018 11:42:10	AD FS	217	None	"A WS-Trust endpoint that was configured could not be opened. 

Additional Data 
Address: https://ad.new.local/adfs/services/trust/2005/windowstransport 
Mode:    WindowsTransport 

Error: 
MSIS0006: A Service Principal Name is not registered for the AD FS service account. "

**Comment by sbidy** [comment]
Mh, I can't see any error that belongs to the behavior.
Do you see the request at your privacyIDEA audit log? Can you also download and try the new V1.2?
I have also add a debugging section to the README - please configure the DebugView as [described](https://github.com/sbidy/privacyIDEA-ADFSProvider#debug).

**Comment by Fadavvi** [comment]
OK, I'll install new version soon as soon possible. But it's may take a while. Close the issue if you want. I'll open a new issue.
