### ISSUE TITLE
Logon wrong realm challange

### ISSUE THREAD

**Issue by Webserve** [sbidy/privacyIDEA-ADFSProvider#39]
I have a strange bug / configuration issue. 

I configured the plugin to use the ADFS realm. But then i logon the ADFS server is using the default "algemeen" realm. (see screenshot)

1. Login goes to the default realm (algemeen in the screenshot)
2. OTP value want to authenticate against to the adfs realm

![Naamloos](https://user-images.githubusercontent.com/666871/80573598-89843f00-8a00-11ea-9ab6-60e15772de0a.png)

Is this a configuration issue or a bug ?

**Comment by sbidy** [comment]
It looks like an error in your provider configuration.
I the [config.yml - line 6](https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/1e5e6b9c2bb9f2e549efc0e6b9079edbb836a2ad/privacyIDEAADFSProvider/config.xml#L6) you must configure the target realm (in your case the "algemeen").

You have to reinstall the provider after the config change.

Currently the provider doesn't supports multiple/dynamic realms (see #36)

**Comment by Webserve** [comment]
In the config i configured "adfs" as realm. Just to be sure i reinstalled the plugin without succes. 
When i set the "adfs" realm as default in privacyidea its working fine. 

```
<server>
  <!-- Server configuration for the privacyIDEA system -->
  <url>https://192.168.x.x</url>
  <!-- define the realm at the privacyIDEA for the ADFS authentication-->
  <realm>adfs</realm>
  <!-- false = ssl cert check disable / true = ssl cert check enabled -->
  <ssl>false</ssl>
  <!-- use UPN as Loginname Attribute / false = sAMAccountName will be used -->
  <upn>false</upn>
  <!-- 
      Provide a administrative user and password for the API.
      Only needed if a challenge must be triggered (e.g. Email or SMS token)!
      If not -> left blank.
  -->

```

**Comment by sbidy** [comment]
You have to change the `<realm>` parameter in the config.xml file. After that you have to run the Uninstall-Powershell and the Install-Powershell again. Please keep in mind that the ADFS service will be restarted (possible short outage).

**Comment by Webserve** [comment]
Hi @sbidy i dont know how to pull a bugfix but there is a typo on line 110 of the file OTPprovider.cs

There is a space in the realm key value. 
```
{ "realm ", realm},
```

I recompiled the source without this space and the issue is resolved. 


This is what the ADFS server posts to the privacyidea at this moment. Thats the reason the privacyidea is reverting back to the default realm.
```
user => 8561  ------ realm_ => adfs  ------ 

```

**Comment by sbidy** [comment]
oh - okay. Thank you!! I should improve my test cases!
Thank you I'll fix that immediately.

**Comment by Webserve** [comment]
Thanks :)
