### ISSUE TITLE
The Plugin should display the challenge message

### ISSUE THREAD

**Issue by cornelinux** [sbidy/privacyIDEA-ADFSProvider#42]
When doing challenge-response with ``triggerchallenge`` the privacyIDEA returns a ``message`` in the JSON response. The contents of this is often useful, since it contains s.th. like "Please enter the OTP value from the Email".
Especially for the indexedSecretToken it contains important information like "Please enter the position 2,3 and 7 of your secret".
Without this information, the user can not answer the challenge.

The message should be inserted about here:
https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/9c668f6164164a1672a81922c8d646d03be93f91/privacyIDEAADFSProvider/Adapter.cs#L96

The call to ``triggerChallenge`` needs to return the message like here:
https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/44907a065c5df08d10704e1ab9c75d90a08ef691/privacyIDEAADFSProvider/OTPprovider.cs#L114

Can the ``triggerChallenge`` method return a tuple of the transaction_id and the message?

You can see the returned messages here:
https://privacyidea.readthedocs.io/en/latest/modules/api/validate.html#get--validate-triggerchallenge

So the code should probably be something like

~~~~c#
                    string message = getJsonNode(responseString, "messages");
~~~~
or ``getJsonNode(responseString, "message")``, since message contains the concatenation of all challenges.

**Comment by sbidy** [comment]
This should not be a big thing - give me the weekend for the first beta 😄 🚀 
But I'll keep this as an optional feature which can be activated in the config (for the 1.3.8).

**Comment by cornelinux** [comment]
Please drop me a note, if you need any input!

**Comment by sbidy** [comment]
Update now available as [1.3.8.2](https://github.com/sbidy/privacyIDEA-ADFSProvider/releases/tag/1.3.8.2) - now should be display the challenge message in the UI (tested with "Questioner Challenge Token")

Please test with your token implementation.

The message can be switched on and off with a config parameter:
https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/1bd05eeef67309daf6d328a79c465e63781d5857/privacyIDEAADFSProvider/config.xml#L12

**Comment by sbidy** [comment]
The massage array will be displayed but maybe no correct formatted!

**Comment by sbidy** [comment]
All messages will be shown up in the UI if multiple tokens are deploy - check version 1.3.8.2.
This should fix the appearance problem from 1.3.8.1.

**Comment by cornelinux** [comment]
Cool, thx!

**Comment by sbidy** [comment]
Any updates? :)

**Comment by cornelinux** [comment]
I am not able to look at it myself. But I got work from a user, that it works out as expected. Thanks a lot! :+1
