### ISSUE TITLE
how to get this provider as the second authentication factor?

### ISSUE THREAD

**Issue by yangboyd** [sbidy/privacyIDEA-ADFSProvider#43]
For office365, I managed to get this as one of the primary authentication method, use can choose when login.

But How can make it as the second factor, after the use login with password, then trigger the challenge, then use input the OTP code?

**Comment by sbidy** [comment]
If you configure/install the provider in the ADFS you can chose in which stage the provider acts as authentication layer.
In Server 2016 and ADFS v4 there are some changes regarding the configuration.

If you configure a "Relaying Party Trust" to your Application (for example Exchange OWA) you have to define a Access Control Policy which defines how hast to authenticate with what type.
For example you can configure MFA only for "external" and/or "untrusted" devices ect.
In ADFS v3 under 2016 there was a "Global Policy" - this was changed in 2019 to a fine granular definition.
In all cases you should have "Form Authentication" as fist and the provider as "additional authentication method".

Please have a look into the official Microsoft documentation for details.
For Office 365 or Azure you have to configure this with the AAD Connect Wizard.

**Comment by yangboyd** [comment]
Thanks!  Finally Got it.
It's latest windows server 2019. AD FS needs Azure Active Directory.
In AAD, I need create Conditional Access Policy to enable MFA. Then the MFA configuration(about Primary/Additional Authentication Methods) in AD FS can work.
