### ISSUE TITLE
Localisation not working

### ISSUE THREAD

**Issue by fefaul** [sbidy/privacyIDEA-ADFSProvider#45]
Hi,

first of all, thanks for the great work you put into this.

Might be I'm doing something wrong, but I can't make changes to the translation work.

If change the config like this and reinstalled the adapted. (Change to authentication came into effect)

`  <interface LCID="1031"> 
    <errormessage>Login fehlgeschlagen. Bitte versuchen Sie es erneut!</errormessage>
    <welcomemessage>Bitte geben Sie ihren PIN und OTP Token ein:</welcomemessage>
    <otptext>OTP Token</otptext>
    <submittext>Submit3</submittext>
    <friendlyname>Sennheiser OTP Token</friendlyname>
    <description>3privacyIDEA ADFS Provider zur Bedienung der API.</description>
    <title>OTP - DE</title>
  </interface>
`

Here is a Screenshot.
Neither the Submit button was changed nor the "Name of the provide. Any idea what I do wrong, or do I have false exceptations here?

![otp_adfs](https://user-images.githubusercontent.com/29343331/89307468-65747180-d671-11ea-8cbd-350029e2d483.png)

**Comment by sbidy** [comment]
The selection of the languages will be based on your client (browser) settings.
Is this behavior alos present in other languages, like English?

**Comment by fefaul** [comment]
I'm pretty sure it is. I've tried changing the language and also tried different browsers.

I'll test again later today and provide more information.

**Comment by fefaul** [comment]
Ok, as always the error is infront of the monitor. :/ After sending the correct language code, I can see the changes.

But what doesn't change is the name of the adapter in the list of MFA options, as shown in the Screenshot above. 
Is it possible to change this at all without modifying the source code? I thought, this is the "Friendly Name" but it doesn't look like.

Thanks for your help.

**Comment by sbidy** [comment]
I'm not sure what name the ADFS shows in this selection. I'll try to reproduce it an have a look into the code.

**Comment by sbidy** [comment]
I should the `friendlyname` property in the config.xml.
Please try to change this parameter in the `LCID="1033"` section. The 1033 is the fallback.

Please keep in mind that the provider has to be reinstalled after changes in the `config.xml`.
