### ISSUE TITLE
ADFSProvider not passing the client IP to privacyIDEA server?

### ISSUE THREAD

**Issue by lazyfai** [sbidy/privacyIDEA-ADFSProvider#46]
I have setup AD FS server and the provider, I found that even I have setup the client IP override option in privacyIDEA server, the "client IP" showing up in privacyIDEA server was always the AD FS server instead of the real client IP. Is it possible to pass the client IP to the privacyIDEA server via the ADFS provider?

**Comment by sbidy** [comment]
For the PrivacyIDEA the ADFS Provider is the "Client". It is really difficult to get the real client IP out of the HTTP request and pass this through the ADFS tho the privacyIDEA.
But in the logs the client ID should be shown up.
