### ISSUE TITLE
OTP pins with only digits are send to privacyIDEA

### ISSUE THREAD

**Issue by myownhost** [sbidy/privacyIDEA-ADFSProvider#6]
We tried the provider and find out that only OTP pins that contain only digits are sent to /validate/check.
I have a short look to your code and find the following line

https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/4aebedcd4a087fabede2ad3fb00a53507278207f/privacyIDEAADFSProvider/OTPprovider.cs#L39

Why did you decide to sent only digits? The token could contain a pin and otp and for the pin it is possible to use other characters then digits.

So my question is, is it possible to delete this line?

Many thanks
Rene

**Comment by cornelinux** [comment]
There could even be OTP tokens, what also allow other elements than digits.
(Like the questionaire token...)

**Comment by sbidy** [comment]
Removed in 1.3
