### ISSUE TITLE
OTP password field is not masked with stars

### ISSUE THREAD

**Issue by myownhost** [sbidy/privacyIDEA-ADFSProvider#7]
Is it possible to change the following line to type="password" for hiding the input characters?

https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/a096ffca29f75ef94ee74785c21547ca5dc39499/privacyIDEAADFSProvider/AuthPage.html#L9

Many thanks
Rene

**Comment by cornelinux** [comment]
This might be sensible, if not only an OTP value (which is not valid after usage anymore) but an OTP PIN/Password and the OTP value are entered and sent to privacyIDEA.

**Comment by sbidy** [comment]
Type changed to password - see releases V1.3.1
