### ISSUE TITLE
Information: ADFS 4.0 - Windows Server 2016 is working

### ISSUE THREAD

**Issue by myownhost** [sbidy/privacyIDEA-ADFSProvider#8]
Hi  @sbidy,

just for your information. 

The privider works fine with ADFS 4.0 on Windows Server 2016.
[https://github.com/sbidy/privacyIDEA-ADFSProvider/blob/master/README.md#features](url)

Kind regards
Rene

**Comment by sbidy** [comment]
Thank you for the feedback!
